web:
  image: kachabros.com/nodejs:0.12
  restart: always

  container_name: kcsot-web

  expose: 3000
  ports: 3000:3000
  external_links: kcsot-mongodb:db
  volumes: 
    - /data/kcsot-prod/web:/home/kacha/programs:ro
  
  mem_limit: 500000000
  command: sh /home/kacha/programs/run.sh
