mongo:
  image: kachabros.com/mongo:3.0.1
  restart: always

  container_name: kcsot-mongodb

  expose: 27017
  volumes: 
    - /data/kcsot-prod/mongodb:/var/lib/mongodb
    - /data/kcsot-prod/mongolog:/var/log/mongodb
  
  mem_limit: 1000000000
  command: mongod -f /etc/mongod.conf
